# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.2.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files

  - repo: https://github.com/asottile/reorder_python_imports
    rev: v3.9.0
    hooks:
      - id: reorder-python-imports
        args:
          - --py37-plus
  - repo: https://github.com/pre-commit/mirrors-eslint
    rev: ''
    hooks:
      - id: eslint
        additional_dependencies:
          - eslint@4.15.0
          - eslint-config-google@0.7.1
          - eslint-loader@1.6.1
          - angular-eslint
          - babel-eslint@6.1.2

  - repo: https://github.com/psf/black
    rev: 23.1.0
    hooks:
      - id: black
        args:
          - --exclude="""\.git |
            \.__pycache__|
            \.hg|
            \.mypy_cache|
            \.tox|
            \.venv|s
            _build|
            buck-out|
            build|
            dist"""

  - repo: https://github.com/pycqa/flake8
    rev: 4.0.1
    hooks:
      - id: flake8
        additional_dependencies:
          - flake8-bugbear
          - flake8-comprehensions
          - flake8-simplify
        exclude: .*/migrations/.*
        args:
          - "--max-line-length=88"
          - "--max-complexity=18"
          - "--select=B,C,E,F,W,T4,B9"
          - "--ignore=E203,E266,E501,W503,F403,F401,E402"
